In [1]:
from platform import python_version

# En produccion sacar, solo se incluye a modo de información
print('Pyton version: {}'.format(python_version()))

Pyton version: 3.10.14

In [2]:
# En produccion sacar, solo se incluye a modo de información
#!jupyter --version

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong>Cargar librerías Warnings, Numpy y Pandas</strong></p>

In [3]:
import warnings
warnings.filterwarnings("ignore", category=Warning)

In [4]:
import numpy as np
np.set_printoptions(suppress=True)

# En produccion eliminar, se incluye por información
print(f'Numpy version: {np.__version__}')

Numpy version: 1.26.4

In [5]:
import pandas as pd
#Configuración de parametros de Pandas para mejor visualización
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.precision', 3)
pd.set_option('plotting.backend', 'matplotlib') 
pd.options.mode.chained_assignment = None

# En produccion eliminar, se incluye por informacion
print(f'Pandas Version: {pd.__version__}')

Pandas Version: 2.2.2

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong>Cargar librería featuretools</strong></p>

In [6]:
import featuretools as ft

# En produccion eliminar, se incluye por informacion
print(f'Featuretools Version: {ft.__version__}')

Featuretools Version: 1.30.0

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong>Carga de conjunto de datos de prueba que trae por defecto featuretools</strong></p>

In [7]:
import joblib as jb
df = pd.DataFrame(jb.load('01AEDAdataV1.bin'))

In [8]:
df.head()

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,icu_id,icu_stay_type,icu_type,pre_icu_los_days,weight,apache_2_diagnosis,apache_3j_diagnosis,apache_post_operative,arf_apache,gcs_eyes_apache,gcs_motor_apache,gcs_unable_apache,gcs_verbal_apache,heart_rate_apache,intubated_apache,map_apache,resprate_apache,temp_apache,ventilated_apache,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_min,d1_heartrate_max,d1_heartrate_min,d1_mbp_max,d1_mbp_min,d1_mbp_noninvasive_max,d1_mbp_noninvasive_min,d1_resprate_max,d1_resprate_min,d1_spo2_max,d1_spo2_min,d1_sysbp_max,d1_sysbp_min,d1_sysbp_noninvasive_max,d1_sysbp_noninvasive_min,d1_temp_max,d1_temp_min,h1_diasbp_max,h1_diasbp_min,h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_min,h1_heartrate_max,h1_heartrate_min,h1_mbp_max,h1_mbp_min,h1_mbp_noninvasive_max,h1_mbp_noninvasive_min,h1_resprate_max,h1_resprate_min,h1_spo2_max,h1_spo2_min,h1_sysbp_max,h1_sysbp_min,h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_min,d1_glucose_max,d1_glucose_min,d1_potassium_max,d1_potassium_min,apache_4a_hospital_death_prob,apache_4a_icu_death_prob,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,66154,118,68,22.73,False,Caucasian,M,180.3,Floor,92,admit,CTICU,0.542,73.9,113,502.01,False,False,3,6,False,4,118,False,40,36.0,39.3,False,68,37,68,37,119,72,89,46,89,46,34,10,100,74,131,73,131.0,73.0,39.9,37.2,68,63,68.0,63.0,119,108,86,85,86,85,26,18,100,74,131,115,131,115,168,109,4.0,3.4,0.1,0.05,False,False,True,False,False,False,False,False,Sepsis,Cardiovascular,False
1,114252,81,77,27.42,False,Caucasian,F,160.0,Floor,90,admit,Med-Surg ICU,0.928,70.2,108,203.01,False,False,1,3,False,1,120,False,46,33.0,35.1,True,95,31,95,31,118,72,120,38,120,38,32,12,100,70,159,67,159.0,67.0,36.3,35.1,61,48,61.0,48.0,114,100,85,57,85,57,31,28,95,70,95,71,95,71,145,128,4.2,3.8,0.47,0.29,False,False,True,False,False,False,False,False,Respiratory,Respiratory,False
2,119783,118,25,31.95,False,Caucasian,F,172.7,Accident & Emergency,93,admit,Med-Surg ICU,0.001,95.3,122,703.03,False,False,3,6,False,5,102,False,68,37.0,36.7,False,88,48,88,48,96,68,102,68,102,68,21,8,98,91,148,105,148.0,105.0,37.0,36.7,88,58,88.0,58.0,96,78,91,83,91,83,20,16,98,91,148,124,148,124,<NA>,<NA>,<NA>,<NA>,0.0,0.0,False,False,False,False,False,False,False,False,Metabolic,Metabolic,False
3,79267,118,81,22.64,True,Caucasian,F,165.1,Operating Room / Recovery,92,admit,CTICU,0.001,61.7,203,1206.03,True,False,4,6,False,5,114,True,60,4.0,34.8,True,48,42,48,42,116,92,84,84,84,84,23,7,100,95,158,84,158.0,84.0,38.0,34.8,62,44,<NA>,<NA>,100,96,92,71,<NA>,<NA>,12,11,100,99,136,106,<NA>,<NA>,185,88,5.0,3.5,0.04,0.03,False,False,False,False,False,False,False,False,Cardiovascular,Cardiovascular,False
4,92056,33,19,<NA>,False,Caucasian,M,188.0,Accident & Emergency,91,admit,Med-Surg ICU,0.074,<NA>,119,601.01,False,False,<NA>,<NA>,True,<NA>,60,False,103,16.0,36.7,False,99,57,99,57,89,60,104,90,104,90,18,16,100,96,147,120,147.0,120.0,37.2,36.7,99,68,99.0,68.0,89,76,104,92,104,92,<NA>,<NA>,100,100,130,120,130,120,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,False,False,False,False,False,False,False,False,Trauma,Trauma,False

In [9]:
#es = ft.demo.load_mock_customer(return_entityset=True)
es = ft.EntitySet(id='Hospital')

es = es.add_dataframe(
    dataframe_name='HospitalDeath',
    dataframe=df,
    #index='id'
)

# es = ft.entity_from_dataframe(entity_id="transactions",
#                                 dataframe=transactions_df,
#                                 index="transaction_id",
#                                 time_index="transaction_time",
#                                 variable_types={"product_id": ft.variable_types.Categorical,
#                                 "zip_code": ft.variable_types.ZIPCode})

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong>Consulta de los datos cargados</strong></p>

In [10]:
es

Entityset: Hospital
  DataFrames:
    HospitalDeath [Rows: 91713, Columns: 83]
  Relationships:
    No relationships

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong>Consulta de los datos cargados de manera gráfica</strong></p>

In [11]:
es.plot()

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong>Consulta datos por tabla</strong></p>

In [14]:
es['HospitalDeath'].head(3)

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,icu_id,icu_stay_type,icu_type,pre_icu_los_days,weight,apache_2_diagnosis,apache_3j_diagnosis,apache_post_operative,arf_apache,gcs_eyes_apache,gcs_motor_apache,gcs_unable_apache,gcs_verbal_apache,heart_rate_apache,intubated_apache,map_apache,resprate_apache,temp_apache,ventilated_apache,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_min,d1_heartrate_max,d1_heartrate_min,d1_mbp_max,d1_mbp_min,d1_mbp_noninvasive_max,d1_mbp_noninvasive_min,d1_resprate_max,d1_resprate_min,d1_spo2_max,d1_spo2_min,d1_sysbp_max,d1_sysbp_min,d1_sysbp_noninvasive_max,d1_sysbp_noninvasive_min,d1_temp_max,d1_temp_min,h1_diasbp_max,h1_diasbp_min,h1_diasbp_noninvasive_max,h1_diasbp_noninvasive_min,h1_heartrate_max,h1_heartrate_min,h1_mbp_max,h1_mbp_min,h1_mbp_noninvasive_max,h1_mbp_noninvasive_min,h1_resprate_max,h1_resprate_min,h1_spo2_max,h1_spo2_min,h1_sysbp_max,h1_sysbp_min,h1_sysbp_noninvasive_max,h1_sysbp_noninvasive_min,d1_glucose_max,d1_glucose_min,d1_potassium_max,d1_potassium_min,apache_4a_hospital_death_prob,apache_4a_icu_death_prob,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
66154,66154,118,68,22.73,False,Caucasian,M,180.3,Floor,92,admit,CTICU,5.417e-01,73.9,113,502.01,False,False,3,6,False,4,118,False,40,36.0,39.3,False,68,37,68,37,119,72,89,46,89,46,34,10,100,74,131,73,131,73.0,39.9,37.2,68,63,68,63,119,108,86,85,86,85,26,18,100,74,131,115,131,115,168,109,4.0,3.4,0.10,0.05,False,False,True,False,False,False,False,False,Sepsis,Cardiovascular,False
114252,114252,81,77,27.42,False,Caucasian,F,160.0,Floor,90,admit,Med-Surg ICU,9.278e-01,70.2,108,203.01,False,False,1,3,False,1,120,False,46,33.0,35.1,True,95,31,95,31,118,72,120,38,120,38,32,12,100,70,159,67,159,67.0,36.3,35.1,61,48,61,48,114,100,85,57,85,57,31,28,95,70,95,71,95,71,145,128,4.2,3.8,0.47,0.29,False,False,True,False,False,False,False,False,Respiratory,Respiratory,False
119783,119783,118,25,31.95,False,Caucasian,F,172.7,Accident & Emergency,93,admit,Med-Surg ICU,6.944e-04,95.3,122,703.03,False,False,3,6,False,5,102,False,68,37.0,36.7,False,88,48,88,48,96,68,102,68,102,68,21,8,98,91,148,105,148,105.0,37.0,36.7,88,58,88,58,96,78,91,83,91,83,20,16,98,91,148,124,148,124,<NA>,<NA>,NaN,NaN,0.00,0.00,False,False,False,False,False,False,False,False,Metabolic,Metabolic,False

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>_____________________________________________________________</strong></p>

In [16]:
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_entity="HospitalDeath",
                                      agg_primitives=["count"],
                                      #trans_primitives=["month"],
                                      max_depth=1)

TypeError: dfs() got an unexpected keyword argument 'target_entity'

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
A que campos de las tablas fue aplicada el <b><i>AutoFE</i></b>, puede ser consultado mediante:</p>

In [35]:
feature_defs

NameError: name 'feature_defs' is not defined

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
El resultado de las operaciones aplicadas sobre la tabla <b>customers</b>, se puedne consultar en el nuevo dataset creado:</p>

In [25]:
feature_matrix

            zip_code  COUNT(sessions)  MONTH(date_of_birth)  MONTH(join_date)
customer_id
5              60091                6                     7                 7
4              60091                8                     8                 4
1              60091                8                     7                 4
3              13244                6                    11                 8
2              13244                7                     8                 4

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
Lo que se obtiene en el nuevo dataset llamado <b>feature_matrix</b> con índice <b>customer_id</b> el <b>campo zip_code</b> al que no se le ha aplicado ninguna operación, a <b>sessions</b> se le aplico el <b>COUNT</b> y a <b>date_of_birth</b> y <b>join_date</b> se les aplicó <b>MONTH</b><BR><BR>
<b><i>Primitiva de agregación</i></b>: calcula un valor único basado en muchas sesiones relacionadas<BR>
<b><i>Primitiva de transformación</i></b>: toma un valor y lo transforme en otro</p> 
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>_____________________________________________________________</strong></p>

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong>Generar un DFS con profundidad 2</strong>:<BR>
El parametro <b>max_depth</b> con valor 1 significa que se aplica a la tabla <b>customers</b>, la tabla <b>sessions</b>  y la tabla <b>transactions</b></p>

In [26]:
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_entity="customers",
                                      agg_primitives=["mean", "sum", "mode"],
                                      trans_primitives=["month", "hour"],
                                      max_depth=2)

In [27]:
feature_defs

[<Feature: zip_code>,
 <Feature: MODE(sessions.device)>,
 <Feature: MEAN(transactions.amount)>,
 <Feature: MODE(transactions.product_id)>,
 <Feature: SUM(transactions.amount)>,
 <Feature: HOUR(date_of_birth)>,
 <Feature: HOUR(join_date)>,
 <Feature: MONTH(date_of_birth)>,
 <Feature: MONTH(join_date)>,
 <Feature: MEAN(sessions.MEAN(transactions.amount))>,
 <Feature: MEAN(sessions.SUM(transactions.amount))>,
 <Feature: MODE(sessions.HOUR(session_start))>,
 <Feature: MODE(sessions.MODE(transactions.product_id))>,
 <Feature: MODE(sessions.MONTH(session_start))>,
 <Feature: SUM(sessions.MEAN(transactions.amount))>,
 <Feature: MODE(transactions.sessions.customer_id)>,
 <Feature: MODE(transactions.sessions.device)>]

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
El resultado de las operaciones aplicadas sobre la tabla <b>customers</b>, se pueden consultar en el nuevo dataset creado:</p>

In [28]:
feature_matrix

,zip_code,MODE(sessions.device),MEAN(transactions.amount),MODE(transactions.product_id),SUM(transactions.amount),HOUR(date_of_birth),HOUR(join_date),MONTH(date_of_birth),MONTH(join_date),MEAN(sessions.MEAN(transactions.amount)),MEAN(sessions.SUM(transactions.amount)),MODE(sessions.HOUR(session_start)),MODE(sessions.MODE(transactions.product_id)),MODE(sessions.MONTH(session_start)),SUM(sessions.MEAN(transactions.amount)),MODE(transactions.sessions.customer_id),MODE(transactions.sessions.device)
customer_id,,,,,,,,,,,,,,,,,
5,60091,mobile,80.375,5,6349.66,0,5,7,7,78.705,1058.277,0,3,1,472.231,5,mobile
4,60091,mobile,80.070,2,8727.68,0,20,8,4,81.207,1090.960,1,1,1,649.658,4,mobile
1,60091,mobile,71.632,4,9025.62,0,10,7,4,72.774,1128.202,6,4,1,582.193,1,mobile
3,13244,desktop,67.060,1,6236.62,0,15,11,8,67.540,1039.437,5,1,1,405.237,3,desktop
2,13244,desktop,77.422,4,7200.28,0,23,8,4,78.415,1028.611,3,3,1,548.906,2,desktop

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
Al nuevo dataframe <b>feature_matrix</b>, se pueden aplicar diversas operaciones propias de <b>Pandas</b></p>

In [32]:
feature_matrix[['MEAN(sessions.SUM(transactions.amount))']].sort_values(by=['customer_id'])

             MEAN(sessions.SUM(transactions.amount))
customer_id
1                                           1128.202
2                                           1028.611
3                                           1039.437
4                                           1090.960
5                                           1058.277

In [33]:
feature_matrix[['MODE(sessions.HOUR(session_start))']].sort_values(by=['customer_id'])

             MODE(sessions.HOUR(session_start))
customer_id
1                                             6
2                                             3
3                                             5
4                                             1
5                                             0

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>_____________________________________________________________</strong></p>

<a id = "1.0"></a>
<p style="font-size:20px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>Feature Primitives</strong></p> 

<p style="font-size:14px;color:#34656d;font-family:'Comic Sans MS';text-align:right;border-radius:5px 5px;"> 
<i>Web:&nbsp;&nbsp;<a href="https://featuretools.alteryx.com/en/stable/getting_started/primitives.html#defining-custom-primitives" target=\"_blank\">Feature Primitives</a></i></p>

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
Las <b><i>Feature Primitives</i></b> son los componentes básicos <b>de Featuretools</b>.<BR>
Definen cálculos individuales que se pueden aplicar a conjuntos de datos sin procesar para crear nuevas características.</p>

<a id = "1.0"></a>
<p style="font-size:20px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
Lista de <b><i>Feature Primitives</i></b>:<BR></p>

In [34]:
ft.list_primitives()

,name,type,dask_compatible,koalas_compatible,description,valid_inputs,return_type
0,trend,aggregation,False,False,Calculates the trend of a variable over time.,"DatetimeTimeIndex, Numeric",Numeric
1,count,aggregation,True,True,"Determines the total number of values, excluding `NaN`.",Index,Numeric
2,skew,aggregation,False,False,Computes the extent to which a distribution differs from a normal distribution.,Numeric,Numeric
3,all,aggregation,True,False,Calculates if all values are 'True' in a list.,Boolean,Boolean
4,last,aggregation,False,False,Determines the last value in a list.,Variable,None
5,num_unique,aggregation,True,True,"Determines the number of distinct values, ignoring `NaN` values.",Discrete,Numeric
6,entropy,aggregation,False,False,Calculates the entropy for a categorical variable,Categorical,Numeric
7,median,aggregation,False,False,Determines the middlemost number in a list of values.,Numeric,Numeric
8,min,aggregation,True,True,"Calculates the smallest value, ignoring `NaN` values.",Numeric,Numeric
9,time_since_first,aggregation,False,False,Calculates the time elapsed since the first datetime (in seconds).,DatetimeTimeIndex,Numeric
10,n_most_common,aggregation,False,False,Determines the `n` most common elements.,Discrete,Discrete
11,percent_true,aggregation,True,False,Determines the percent of `True` values.,Boolean,Numeric
12,num_true,aggregation,True,False,Counts the number of `True` values.,Boolean,Numeric
13,time_since_last,aggregation,False,False,Calculates the time elapsed since the last datetime (default in seconds).,DatetimeTimeIndex,Numeric
14,sum,aggregation,True,True,"Calculates the total addition, ignoring `NaN`.",Numeric,Numeric
15,any,aggregation,True,False,Determines if any value is 'True' in a list.,Boolean,Boolean
16,first,aggregation,False,False,Determines the first value in a list.,Variable,None
17,max,aggregation,True,True,"Calculates the highest value, ignoring `NaN` values.",Numeric,Numeric
18,avg_time_between,aggregation,False,False,Computes the average number of seconds between consecutive events.,DatetimeTimeIndex,Numeric
19,mean,aggregation,True,True,Computes the average for a list of values.,Numeric,Numeric
20,mode,aggregation,False,False,Determines the most commonly repeated value.,Discrete,None
21,std,aggregation,True,True,"Computes the dispersion relative to the mean value, ignoring `NaN`.",Numeric,Numeric
22,num_words,transform,True,True,Determines the number of words in a string by counting the spaces.,NaturalLanguage,Numeric
23,not_equal,transform,True,False,Determines if values in one list are not equal to another list.,Variable,Boolean
24,subtract_numeric,transform,True,False,Element-wise subtraction of two lists.,Numeric,Numeric
25,cum_max,transform,False,False,Calculates the cumulative maximum.,Numeric,Numeric
26,year,transform,True,True,Determines the year value of a datetime.,Datetime,Ordinal
27,num_characters,transform,True,True,Calculates the number of characters in a string.,NaturalLanguage,Numeric
28,and,transform,True,True,Element-wise logical AND of two lists.,Boolean,Boolean
29,modulo_numeric,transform,True,True,Element-wise modulo of two lists.,Numeric,Numeric
30,multiply_numeric,transform,True,True,Element-wise multiplication of two lists.,"Numeric, Boolean",Numeric
31,longitude,transform,False,False,Returns the second tuple value in a list of LatLong tuples.,LatLong,Numeric
32,minute,transform,True,True,Determines the minutes value of a datetime.,Datetime,Numeric
33,absolute,transform,True,True,Computes the absolute value of a number.,Numeric,Numeric
34,equal_scalar,transform,True,True,Determines if values in a list are equal to a given scalar.,Variable,Boolean
35,day,transform,True,True,Determines the day of the month from a datetime.,Datetime,Ordinal
36,is_weekend,transform,True,True,Determines if a date falls on a weekend.,Datetime,Boolean
37,not,transform,True,True,Negates a boolean value.,Boolean,Boolean
38,less_than_equal_to_scalar,transform,True,True,Determines if values are less than or equal to a given scalar.,"Ordinal, Datetime, Numeric",Boolean
39,cum_count,transform,False,False,Calculates the cumulative count.,"Id, Discrete",Numeric
40,age,transform,True,False,Calculates the age in years as a floating point number given a,DateOfBirth,Numeric
41,negate,transform,True,True,Negates a numeric value.,Numeric,Numeric
42,month,transform,True,True,Determines the month value of a datetime.,Datetime,Ordinal
43,less_than_scalar,transform,True,True,Determines if values are less than a given scalar.,"Ordinal, Datetime, Numeric",Boolean
44,is_null,transform,True,True,Determines if a value is null.,Variable,Boolean
45,url_to_protocol,transform,False,False,Determines the protocol (http or https) of a url.,URL,Categorical
46,cum_min,transform,False,False,Calculates the cumulative minimum.,Numeric,Numeric
47,modulo_numeric_scalar,transform,True,True,Return the modulo of each element in the list by a scalar.,Numeric,Numeric
48,cum_sum,transform,False,False,Calculates the cumulative sum.,Numeric,Numeric
49,greater_than_scalar,transform,True,True,Determines if values are greater than a given scalar.,"Ordinal, Datetime, Numeric",Boolean
50,isin,transform,True,True,Determines whether a value is present in a provided list.,Variable,Boolean
51,not_equal_scalar,transform,True,True,Determines if values in a list are not equal to a given scalar.,Variable,Boolean
52,multiply_numeric_scalar,transform,True,True,Multiply each element in the list by a scalar.,Numeric,Numeric
53,divide_numeric_scalar,transform,True,True,Divide each element in the list by a scalar.,Numeric,Numeric
54,greater_than,transform,True,False,Determines if values in one list are greater than another list.,"Ordinal, Datetime, Numeric",Boolean
55,time_since,transform,True,False,Calculates time from a value to a specified cutoff datetime.,Datetime,Numeric
56,email_address_to_domain,transform,False,False,Determines the domain of an email,EmailAddress,Categorical
57,equal,transform,True,True,Determines if values in one list are equal to another list.,Variable,Boolean
58,less_than,transform,True,True,Determines if values in one list are less than another list.,"Ordinal, Datetime, Numeric",Boolean
59,add_numeric,transform,True,True,Element-wise addition of two lists.,Numeric,Numeric
60,url_to_tld,transform,False,False,Determines the top level domain of a url.,URL,Categorical
61,multiply_boolean,transform,True,False,Element-wise multiplication of two lists of boolean values.,Boolean,Boolean
62,second,transform,True,True,Determines the seconds value of a datetime.,Datetime,Numeric
63,percentile,transform,False,False,Determines the percentile rank for each value in a list.,Numeric,Numeric
64,add_numeric_scalar,transform,True,True,Add a scalar to each value in the list.,Numeric,Numeric
65,scalar_subtract_numeric_feature,transform,True,True,Subtract each value in the list from a given scalar.,Numeric,Numeric
66,cum_mean,transform,False,False,Calculates the cumulative mean.,Numeric,Numeric
67,is_free_email_domain,transform,False,False,Determines if an email address is from a free email domain.,EmailAddress,Boolean
68,diff,transform,False,False,Compute the difference between the value in a list and the,Numeric,Numeric
69,or,transform,True,True,Element-wise logical OR of two lists.,Boolean,Boolean
70,less_than_equal_to,transform,True,True,Determines if values in one list are less than or equal to another list.,"Ordinal, Datetime, Numeric",Boolean
71,greater_than_equal_to_scalar,transform,True,True,Determines if values are greater than or equal to a given scalar.,"Ordinal, Datetime, Numeric",Boolean
72,week,transform,True,True,Determines the week of the year from a datetime.,Datetime,Ordinal
73,url_to_domain,transform,False,False,Determines the domain of a url.,URL,Categorical
74,hour,transform,True,True,Determines the hour value of a datetime.,Datetime,Ordinal
75,divide_by_feature,transform,True,True,Divide a scalar by each value in the list.,Numeric,Numeric
76,time_since_previous,transform,False,False,Compute the time since the previous entry in a list.,DatetimeTimeIndex,Numeric
77,greater_than_equal_to,transform,True,True,Determines if values in one list are greater than or equal to another list.,"Ordinal, Datetime, Numeric",Boolean
78,haversine,transform,False,False,Calculates the approximate haversine distance between two LatLong,LatLong,Numeric
79,latitude,transform,False,False,Returns the first tuple value in a list of LatLong tuples.,LatLong,Numeric
80,subtract_numeric_scalar,transform,True,True,Subtract a scalar from each element in the list.,Numeric,Numeric
81,divide_numeric,transform,True,True,Element-wise division of two lists.,Numeric,Numeric
82,modulo_by_feature,transform,True,True,Return the modulo of a scalar by each element in the list.,Numeric,Numeric
83,weekday,transform,True,True,Determines the day of the week from a datetime.,Datetime,Ordinal

<a id = "1.0"></a>
<p style="font-size:14px;color:#34656d;font-family:'Comic Sans MS';text-align:right;border-radius:5px 5px;">    
<i>Fuente:&nbsp;&nbsp;<a href="https://primitives.featurelabs.com" target=\"_blank\">Feature Primitives List</a></i></p> 
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong><u>Comentario:</u></strong><br>    
Un excelente ejercicio para convertise en experto en <b><i>AutoFE</i></b>, es utilizar esta lista para experimentar con algoritmos.</p>

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
Las <b><i>Feature Primitives</i></b> permiten definir también eventos de tiempo</b>, como sera <b><i>mean</i></b> <b><i>max</i></b> - <b><i>min</i></b> - <b><i>std</i></b> - <b><i>skew</i> - <b><i>time_since_previous</i></b></p>

In [43]:
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_entity="customers",
                                      agg_primitives=["mean", "max", "min", "std", "skew"],
                                      trans_primitives=["time_since_previous"],)

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<strong><u>Coeficiente de Asimetría</a>:</u></strong><br>
<b><i>SKEW</i></b>: Calcula la asimetría de un conjunto de datos. Indica la simetría del conjunto de datos con respecto a la media.</p>
<p style="font-size:14px;color:#34656d;font-family:'Comic Sans MS';text-align:right;border-radius:5px 5px;">
<i>Fuente:&nbsp;&nbsp;<a href="https://support.google.com/docs/answer/3094101?hl=es-419#:~:text=COEFICIENTE.-,ASIMETRIA%20(SKEW),con%20respecto%20a%20la%20media" target=\"_blank\">SKEW</a></i></p>

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
Campos a los cuales fue aplicado el <b><i>AutoFE</i></b></p>

In [44]:
feature_defs

[<Feature: zip_code>,
 <Feature: MAX(transactions.amount)>,
 <Feature: MEAN(transactions.amount)>,
 <Feature: MIN(transactions.amount)>,
 <Feature: SKEW(transactions.amount)>,
 <Feature: STD(transactions.amount)>,
 <Feature: TIME_SINCE_PREVIOUS(join_date)>,
 <Feature: MAX(sessions.MEAN(transactions.amount))>,
 <Feature: MAX(sessions.MIN(transactions.amount))>,
 <Feature: MAX(sessions.SKEW(transactions.amount))>,
 <Feature: MAX(sessions.STD(transactions.amount))>,
 <Feature: MAX(sessions.TIME_SINCE_PREVIOUS(session_start))>,
 <Feature: MEAN(sessions.MAX(transactions.amount))>,
 <Feature: MEAN(sessions.MEAN(transactions.amount))>,
 <Feature: MEAN(sessions.MIN(transactions.amount))>,
 <Feature: MEAN(sessions.SKEW(transactions.amount))>,
 <Feature: MEAN(sessions.STD(transactions.amount))>,
 <Feature: MEAN(sessions.TIME_SINCE_PREVIOUS(session_start))>,
 <Feature: MIN(sessions.MAX(transactions.amount))>,
 <Feature: MIN(sessions.MEAN(transactions.amount))>,
 <Feature: MIN(sessions.SKEW(transactions.amount))>,
 <Feature: MIN(sessions.STD(transactions.amount))>,
 <Feature: MIN(sessions.TIME_SINCE_PREVIOUS(session_start))>,
 <Feature: SKEW(sessions.MAX(transactions.amount))>,
 <Feature: SKEW(sessions.MEAN(transactions.amount))>,
 <Feature: SKEW(sessions.MIN(transactions.amount))>,
 <Feature: SKEW(sessions.STD(transactions.amount))>,
 <Feature: SKEW(sessions.TIME_SINCE_PREVIOUS(session_start))>,
 <Feature: STD(sessions.MAX(transactions.amount))>,
 <Feature: STD(sessions.MEAN(transactions.amount))>,
 <Feature: STD(sessions.MIN(transactions.amount))>,
 <Feature: STD(sessions.SKEW(transactions.amount))>,
 <Feature: STD(sessions.TIME_SINCE_PREVIOUS(session_start))>]

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<b>Dataset resultante</b></p>

In [45]:
feature_matrix.head()

,zip_code,MAX(transactions.amount),MEAN(transactions.amount),MIN(transactions.amount),SKEW(transactions.amount),STD(transactions.amount),TIME_SINCE_PREVIOUS(join_date),MAX(sessions.MEAN(transactions.amount)),MAX(sessions.MIN(transactions.amount)),MAX(sessions.SKEW(transactions.amount)),MAX(sessions.STD(transactions.amount)),MAX(sessions.TIME_SINCE_PREVIOUS(session_start)),MEAN(sessions.MAX(transactions.amount)),MEAN(sessions.MEAN(transactions.amount)),MEAN(sessions.MIN(transactions.amount)),MEAN(sessions.SKEW(transactions.amount)),MEAN(sessions.STD(transactions.amount)),MEAN(sessions.TIME_SINCE_PREVIOUS(session_start)),MIN(sessions.MAX(transactions.amount)),MIN(sessions.MEAN(transactions.amount)),MIN(sessions.SKEW(transactions.amount)),MIN(sessions.STD(transactions.amount)),MIN(sessions.TIME_SINCE_PREVIOUS(session_start)),SKEW(sessions.MAX(transactions.amount)),SKEW(sessions.MEAN(transactions.amount)),SKEW(sessions.MIN(transactions.amount)),SKEW(sessions.STD(transactions.amount)),SKEW(sessions.TIME_SINCE_PREVIOUS(session_start)),STD(sessions.MAX(transactions.amount)),STD(sessions.MEAN(transactions.amount)),STD(sessions.MIN(transactions.amount)),STD(sessions.SKEW(transactions.amount)),STD(sessions.TIME_SINCE_PREVIOUS(session_start))
customer_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5,60091,149.02,80.375,7.55,-0.026,44.096,NaN,94.482,20.65,0.602,51.149,1170.0,139.960,78.705,14.415,2.397e-03,43.312,1007.500,128.51,66.667,-0.539,36.735,715.0,-0.334,0.335,-0.470,0.205,-1.507,7.928,11.007,4.961,0.415,157.884
4,60091,149.95,80.070,5.73,-0.036,45.069,2.295e+07,110.450,54.83,0.383,54.294,1625.0,144.749,81.207,16.439,3.455e-04,44.516,999.375,139.20,70.638,-0.712,29.026,650.0,0.027,1.981,2.104,-1.066,1.065,3.514,13.027,16.961,0.388,308.689
1,60091,139.43,71.632,5.81,0.020,40.442,7.440e+05,88.756,26.36,0.640,46.906,1170.0,132.246,72.774,9.824,-5.952e-02,39.093,966.875,118.90,50.623,-1.038,30.450,715.0,-0.780,-0.425,2.440,-0.312,-0.255,7.322,13.759,6.955,0.589,171.754
3,13244,149.15,67.060,5.89,0.418,43.683,1.021e+07,82.109,20.06,0.855,50.110,1170.0,141.272,67.540,11.035,3.810e-01,42.883,888.333,126.74,55.579,-0.289,35.705,650.0,-0.941,0.679,1.001,-0.246,0.435,10.724,11.174,5.424,0.429,177.614
2,13244,146.81,77.422,8.73,0.098,37.705,2.128e+07,96.581,56.46,0.756,47.936,975.0,133.090,78.415,22.086,-3.966e-02,36.957,725.833,100.04,61.910,-0.764,27.839,520.0,-1.539,0.235,2.155,0.013,0.163,17.222,11.477,15.874,0.510,194.639

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
Se pueden aplicar operaciones al nuevo dataset:</p>

In [46]:
feature_matrix[["MEAN(sessions.TIME_SINCE_PREVIOUS(session_start))",
                "MAX(sessions.TIME_SINCE_PREVIOUS(session_start))",
                "MIN(sessions.TIME_SINCE_PREVIOUS(session_start))",
                "STD(sessions.TIME_SINCE_PREVIOUS(session_start))",
                "SKEW(sessions.TIME_SINCE_PREVIOUS(session_start))",]]

,MEAN(sessions.TIME_SINCE_PREVIOUS(session_start)),MAX(sessions.TIME_SINCE_PREVIOUS(session_start)),MIN(sessions.TIME_SINCE_PREVIOUS(session_start)),STD(sessions.TIME_SINCE_PREVIOUS(session_start)),SKEW(sessions.TIME_SINCE_PREVIOUS(session_start))
customer_id,,,,,
5,1007.500,1170.0,715.0,157.884,-1.507
4,999.375,1625.0,650.0,308.689,1.065
1,966.875,1170.0,715.0,171.754,-0.255
3,888.333,1170.0,650.0,177.614,0.435
2,725.833,975.0,520.0,194.639,0.163

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>_____________________________________________________________</strong></p>

<a id = "1.0"></a>
<p style="font-size:20px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<b> Aggregation Primitive vs Transform Primitive</b></p>

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<b><i>Aggregation Primitive</i></b>: Estas primitivas toman diversas instancias como entrada y entregan un valor único</p>

![AG](./img/02.png)

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<b><i>Trasform Primitive</i></b>: Estas primitivas toman una o más variables de una entidad como entrada y generan una nueva variable para esa entidad</p>

![TR](./img/03.png)

<a id = "1.0"></a>
<p style="font-size:14px;color:#34656d;font-family:'Comic Sans MS';text-align:right;border-radius:5px 5px;">
<i>Fuente:&nbsp;&nbsp;<a href="https://featuretools.alteryx.com/en/stable/getting_started/primitives.html#Aggregation-vs-Transform-Primitive" target=\"_blank\">Aggregation vs Transform Primitive</a></i></p>

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>_____________________________________________________________</strong></p>

<a id = "1.0"></a>
<p style="font-size:20px;color:#34656d;font-family:'Comic Sans MS';text-align:left;border-radius:5px 5px;">
<b>Listado de Tipos de Variables</b></p>

In [48]:
from featuretools.variable_types import graph_variable_types

In [49]:
graph_variable_types()

In [50]:
from featuretools.variable_types import list_variable_types

In [51]:
list_variable_types()

,name,type_string,description
0,Unknown,unknown,None
1,Discrete,discrete,Superclass representing variables that take on discrete values
2,Categorical,categorical,"Represents variables that can take an unordered discrete values\n\n Args:\n categories (list) : List of categories. If left blank, inferred from data.\n"
3,Id,id,Represents variables that identify another entity
4,ZIPCode,zip_code,Represents a postal address in the United States.\n Consists of a series of digits which are casts as\n string. Five digit and 9 digit zipcodes are supported.\n
5,CountryCode,country_code,Represents an ISO-3166 standard country code.\n ISO 3166-1 (countries) are supported. These codes\n should be in the Alpha-2 format.\n e.g. United States of America = US\n
6,SubRegionCode,sub_region_code,"Represents an ISO-3166 standard sub-region code.\n ISO 3166-2 codes (sub-regions are supported. These codes\n should be in the Alpha-2 format.\n e.g. United States of America, Arizona = US-AZ\n"
7,Ordinal,ordinal,Represents variables that take on an ordered discrete value
8,Boolean,boolean,"Represents variables that take on one of two values\n\n Args:\n true_values (list) : List of valued true values. Defaults to [1, True, ""true"", ""True"", ""yes"", ""t"", ""T""]\n false_values (list): List of valued false values. Defaults to [0, False, ""false"", ""False"", ""no"", ""f"", ""F""]\n"
9,Numeric,numeric,"Represents variables that contain numeric values\n\n Args:\n range (list, optional) : List of start and end. Can use inf and -inf to represent infinity. Unconstrained if not specified.\n start_inclusive (bool, optional) : Whether or not range includes the start value.\n end_inclusive (bool, optional) : Whether or not range includes the end value\n\n Attributes:\n max (float)\n min (float)\n std (float)\n mean (float)\n"
10,NumericTimeIndex,numeric_time_index,Represents time index of entity that is numeric
11,Index,index,Represents variables that uniquely identify an instance of an entity\n\n Attributes:\n count (int)\n
12,Datetime,datetime,Represents variables that are points in time\n\n Args:\n format (str): Python datetime format string documented `here <http://strftime.org/>`_.\n
13,DatetimeTimeIndex,datetime_time_index,Represents time index of entity that is a datetime
14,DateOfBirth,date_of_birth,Represents a date of birth as a datetime
15,TimeIndex,time_index,Represents time index of entity
16,Timedelta,timedelta,"Represents variables that are timedeltas\n\n Args:\n range (list, optional) : List of start and end of allowed range in seconds. Can use inf and -inf to represent infinity. Unconstrained if not specified.\n start_inclusive (bool, optional) : Whether or not range includes the start value.\n end_inclusive (bool, optional) : Whether or not range includes the end value\n"
17,NaturalLanguage,natural_language,Represents variables that are arbitary strings
18,LatLong,lat_long,"Represents an ordered pair (Latitude, Longitude)\n To make a latlong in a dataframe do\n data['latlong'] = data[['latitude', 'longitude']].apply(tuple, axis=1)\n"
19,IPAddress,ip_address,Represents a computer network address. Represented\n in dotted-decimal notation. IPv4 and IPv6 are supported.\n
20,FullName,full_name,"Represents a person's full name. May consist of a\n first name, last name, and a title.\n"
21,EmailAddress,email_address,"Represents an email box to which email message are sent.\n Consists of a local-part, an @ symbol, and a domain.\n"
22,URL,url,Represents a valid web url (with or without http/www)
23,PhoneNumber,phone_number,Represents any valid phone number.\n Can be with/without parenthesis.\n Can be with/without area/country codes.\n
24,FilePath,file_path,"Represents a valid filepath, absolute or relative"

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>_____________________________________________________________</strong></p>

<a id = "1.0"></a>
<p style="font-size:15px;color:#34656d;font-family:'Comic Sans MS';text-align:center;border-radius:5px 5px;">
<strong>_____________________________________________________________</strong></p>